# ===================================================
# KONFIGURASI PROJECT — sesuaikan untuk tiap project
# ===================================================

# URL aplikasi yang diuji
base.url=https://www.example.com

# Browser: chrome | firefox | edge
browser=chrome

# Mode headless: true | false
headless=false

# Timeout (detik)
implicit.wait=10
explicit.wait=15
page.load.timeout=30

# Environment: dev | staging | production
environment=staging

# Screenshot: hanya saat gagal (on_failure) atau selalu (always)
screenshot=on_failure

# Folder output screenshot
screenshot.path=target/screenshots
